# -*- coding: utf-8 -*-
"""Lecture19 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9dYmv1NCpjlXXiBQEKQMlII9lbEkevA
"""

class Car:
  def __init__(self,brand,color):
    self.brand=brand
    self.color=color
  def start(self):
    print(f"The {self.brand} {self.color} car has started")
  def stop(self):
    print(f"The {self.brand} {self.color} car has stopped")

car1=Car("Toyota","Red")
car2=Car("Honda","Blue")

car1.start()
car2.stop()

student={
    "name" : "Adil",
    "age" : 20,
    "Skill" : "Ai"
}

print("Students Age is ", student["age"])

student["age"]=21
print(student)

for key,value in student.items():
  print(key ,":", value )

student={
    "Id" : 1,
    "Profile": {
        "Name" : "Adil",
        "SKill" : ["Python","AI"]
    }
}

print(student)
print(student["Profile"]["SKill"][0])

import json
data='{ "Name": "Adil" ,"Age" :"20" }'
python_data=json.loads(data)
print(python_data)

for key,value in python_data.items():
  print(key, ":" , value)

file=open("data.txt","w")
contant=file.write("Hello how are you")
print(contant)
file.close() # Close after writing

file=open("data.txt","r") # Open in read mode
contant2=file.read()
print(contant2)
file.close()
with open("data.txt","a") as file:
  file.write("\nI am fine")
with open("data.txt","r") as file:
  Read=file.read()
  print(Read)

from typing_extensions import Writer
import csv
with open ("data.csv","w")as file:
  Writers=csv.writer(file)
  Writers.writerow(["Name :","Result"])
  Writers.writerow(["Adil :","Pass"])

with open ("data.csv","r")as file:
  Reader=csv.reader(file)
  for row in Reader:
    print(row)

import csv

with open("data.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        print(row["Name :"], row["Result"])

!pip install transformers

from transformers import pipeline

# Load model
pipe = pipeline(
    "text-generation",
    model="koutch/qwen_qwen3-instruct-4b_train_sft_train_code",
    trust_remote_code=True
)

# Take input from user
user_input = input("Enter your question: ")

# Create messages dynamically
messages = [
    {"role": "user", "content": user_input},
]

# Generate response
response = pipe(messages)

# Print output clearly
print("\nModel Response:\n")
print(response[0]["generated_text"])

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="koutch/qwen_qwen3-instruct-4b_train_sft_train_code",
    device_map="auto"
)

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Chat ended.")
        break

    messages = [{"role": "user", "content": user_input}]
    output = pipe(messages, max_new_tokens=500)

    # ✅ CLEAN OUTPUT
    assistant_reply = output[0]["generated_text"][-1]["content"]
    print("AI:", assistant_reply)

class Employee:
  def  __init__(self,name,Role,Salery):
    self.name=name
    self.role=Role
    self.Salery=Salery



  def info(self):
    print(f"{self.name} has and perform  {self.role} Technolgy And this Salery {self.Salery}")


emp1=Employee("Adil","AI Engineer", 50000)
emp2=Employee("Ali","block Chain", 40000)
emp1.info()
emp2.info()